VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IBenefitForm"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Function ListBenefits(Optional ByVal Index As Long = 0) As Boolean

End Function

Public Function BenefitToScreen(Optional ByVal lTag As Long = -1, Optional ByVal lIndex As Long = -1) As IBenefitClass
      
End Function
    
Public Sub ClearFields()

End Sub

Public Sub AddBenefit()

End Sub

Public Function Remove(i As Long) As Boolean

End Function

Public Property Let bentype(newbenclass As benClass)

End Property

Public Property Get bentype() As benClass

End Property

