VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IProgress"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Public Function PreProgress(ViewPrg As Boolean, PrintPrg As Boolean, prg As Object, ByVal lProgressType As Long) As Boolean

End Function
Public Function PostProgress(ViewPrg As Boolean, PrintPrg As Boolean, prg As Object, ByVal lProgressType As Long) As Boolean

End Function
Public Function Progress(ViewPrg As Boolean, PrintPrg As Boolean, prg As Object, ByVal lProgressType As Long) As Boolean
  
End Function
Public Sub ViewPrg()

End Sub
Public Sub PrintPrg()

End Sub

