VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IPageMarkup"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'cadxx new
Option Explicit

'change the attributes here
Public Sub HTMLElement(Attributes As Collection, ByVal ElementType As String, TextBefore As String, TextAfter As String, Optional ByVal InnerHTML As String)
    

End Sub
Public Sub CSSURL(ByRef url As String)

End Sub



