@echo off
SET WINSYS=C:\WINDOWS\SYSTEM
if X%windir%X == XC:\WINNTX SET WINSYS=C:\WINNT\SYSTEM32
if X%windir%X == Xc:\winntX SET WINSYS=C:\WINNT\SYSTEM32
if X%windir%X == Xc:\WINNTX SET WINSYS=C:\WINNT\SYSTEM32
if X%windir%X == XC:\winntX SET WINSYS=C:\WINNT\SYSTEM32
CALL VERCHK.BAT TCSBASE.OLB R:\VC\TCSBASE\RELEASE
CALL VERCHK.BAT TCSCCORE.DLL R:\VC\TCSCCORE\RELEASE
CALL VERCHK.BAT TCSPROG.OCX R:\VC\TCSPROG\RELEASE
CALL VERCHK.BAT TCSNOTES.DLL R:\VC\TCSNOTES\RELEASE
CALL VERCHK.BAT TCSBG.OCX R:\VC\TCSBG\RELEASE