VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "DefaultStatic"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Value As String
Public DataType As DATABASE_FIELD_TYPES
Public FieldName As String
Public DestField As String

Public CopyFieldName As String
Public CopyFieldKey As Long
