VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IImportForm"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Get FormType() As IMPORT_GOTOFORM

End Property

Public Property Get ImpWiz() As ImportWizard

End Property

Public Property Set ImpWiz(NewValue As ImportWizard)

End Property
