
        {ADDRESS}
{NEWPAGE}
{normal}








{companyname}
PAYE reference: {payeref}
{date}

{normal}{name}
{address}
Personal reference: {pnumber}
National Insurance number : {ninumber}

{normal}Dear {FIRSTNAME}

{bold}DETAILS OF EXPENSES, PAYMENTS AND BENEFITS {TAXYEAR}

{normal}The following information will be provided to HMRC in relation to
expenses, payments and benefits provided to you by {companyname}
between {TAX_YEAR_START} and {TAX_YEAR_END}.

{table}

{bold}It is your responsibility to check that the details shown are correct.  Any errors must be 
communicated to {contactname} before {RESPONSE_DATE} on the form enclosed.

{newpage}






{bold}Record Keeping
{normal}It is important that you keep this information in a safe place as you may be required to
provide the details in it on your {TAXYEAR} tax return.  Whether or not you receive a tax return,
you are required by law to keep this information until at least {KEEP_DETAILS_UNTIL}, and possibly
longer depending on your personal circumstances.  You should also keep details of any expenses
paid for you in relation to your employment for which you intend to make a tax claim,
including business mileage records.

{bold}Dispensations and PAYE Settlement Agreements
{normal}Certain benefits and expenses are not included on the P11D information. These items are
not reported as they are included in a PAYE settlement agreement or are covered by a
dispensation agreed with HMRC.  A dispensation is an agreement with 
HMRC not to report certain benefits as there is no tax payable on them by our
employees.  An PAYE settlement agreement is an agreement for {companyname}
to pay the tax due on certain benefits provided on behalf of the employees.

{normal}No further tax is due on these items and you do not need to include details of items
covered by a dispensation or PAYE settlement agreement on your tax return.  If you are
uncertain whether an item is covered by a dispensation of PAYE settlement agreement please
contact {contactname} on {contactnum} for further information.

{bold}Contact Information
{normal}If you have any questions concerning the information contained in this letter please
contact {contactname} on {contactnum}.



Yours sincerely



{signatory}

{newpage}






{bold}To:         {signatory}

From:    {name}



DETAILS OF EXPENSES, PAYMENTS AND BENEFITS IN KIND:


{normal}Please tick the appropriate box. 

Sign this form and return it to {contactname} before {RESPONSE_DATE}.

{normal}I confirm that

  __    the details of expenses, payments and benefits in kind provided to me is correct
          and complete to the best of my knowledge.

  __    the details of expenses, payments and benefits in kind provided to me require
          amending as detailed below.


{bold}Signed                                                              Date





{bold}DETAILS OF AMENDMENTS:
