VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IReportForm"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Ext_KEY = "SavedWithClassBuilder" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
Option Explicit

Public Property Get FormType() As REPORTW_GOTOFORM

End Property

Public Property Set ReportWizard(NewValue As ReportWizard)

End Property

Public Property Set ReportDetails(NewValue As ReportDetails)

End Property

Public Property Set ReportFields(NewValue As Collection)

End Property

Public Property Set ReportDataSets(NewValue As DataSetCollection)

End Property

