Attribute VB_Name = "AutoReport"
Option Explicit

Public Const one_cm As Single = 1440 / 2.54
Public Const MINCOLWIDTH As Single = one_cm
Public Const MINEMPTYCOLWIDTH As Single = one_cm / 4
Public Const MININTERCOLSPACE As Single = one_cm / 4

Public Const MINLEFTMARGIN As Single = one_cm / 2
Public Const MINRIGHTMARGIN As Single = one_cm / 2
Public Const ADJRIGHTALIGN As Single = one_cm / 4
Public Const ADJSPACING As Single = one_cm / 5

Public Const PREVIEWROWS = 25
 
