VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IDebugMenu"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Function DatabaseMenuItem(ByVal MenuName As String) As Boolean

End Function

Public Function RepairCompactAvailable() As Boolean

End Function

Public Function SQLAvailable() As Boolean

End Function

 
