Attribute VB_Name = "Const"
Option Explicit



Public Enum RegistryKeyAction
  REGISTRY_KEY_READ
  REGISTRY_KEY_WRITE
End Enum

Public Enum MailOptionAction
  MAILOPTION_UNCHECKED = 0
  MAILOPTION_CHECKED = 1
  MAILOPTION_DISABLE = 2
  MAILOPTION_ENABLE = 4
End Enum

Global Const S_REGISTRY_APPNAME As String = "ATCMAIL"
Global Const S_REGISTRY_SECTION As String = "Settings"
Global Const S_DEFAULT_TEST_RECIPIENT As String = "p11d@gmail.com"

Global Const S_IDSMAIL_DEBUGAPP_DIR As String = "OLESVRS"
Global Const S_IDSMAIL_DEBUGAPP_FILE As String = "MAILDI32.EXE"
Global Const S_IDSMAIL_DEBUGAPP_OUTPUT_FILE As String = "MS_LOG.TXT"

Global Const IDSM_QUERY_NOTES_OR_CCMAIL = 25
Global Const IDSM_ENUM_CCMAIL = 11
Global Const IDSM_ENUM_NOTES = 63
Global Const IDSM_ENUM_NO_VIM = 0

'Items 1 -6 held in Enum IDMS_MESSAGE_ITEMS
Global Const IDSM_ITM_ATTACHMENT_NAME = 7
Global Const IDSM_ITM_ATTACHMENT_COUNT = 8
Global Const IDSM_ITM_FROM = 9
Global Const IDSM_ITM_DATE_SENT = 10
Global Const IDSM_ITM_STATE = 11
Global Const IDSM_ITM_CERTIFIED = 12
Global Const IDSM_ITM_MESSAGE_ID = 23
Global Const IDSM_ITM_RETURN_PATH = 20
Global Const IDSM_ITM_DATE_DELIVERED = 32
Global Const IDSM_ITM_CONVERSATION_INDEX = 33
Global Const IDSM_ITM_CONVERSATION_TOPIC = 34
Global Const IDSM_ITM_PARENT_MESSAGE_ID = 35

Global Const IDSM_ITM_IMPORTANCE = 50
Global Const IDSM_ITM_DELIVERY_PRIORITY = 51
Global Const IDSM_ITM_DELIVERY_REPORT = 52
Global Const IDSM_ITM_SIGNED = 53
Global Const IDSM_ITM_ENCRYPTED = 54
Global Const IDSM_ITM_PREVENT_COPYING = 55
Global Const IDSM_ITM_SENSITIVITY = 56

'---- For GetInterfaceString -----
Global Const IDSM_ITM_IFC_FILESPEC = 40
Global Const IDSM_ITM_IFC_COMPANY = 41
Global Const IDSM_ITM_IFC_DESCRIPTION = 42
Global Const IDSM_ITM_IFC_FILE_VERSION = 43
Global Const IDSM_ITM_IFC_PROD_VERSION = 44
Global Const IDSM_ITM_IFC_COPYRIGHT = 45

'--- Internet Mail (SMTP/POP) Only ---
Global Const IDSM_ITM_RAW_HEADERS = 21
Global Const IDSM_ITM_X_MAILER = 22
Global Const IDSM_ITM_CONTENT_LENGTH = 24
Global Const IDSM_ITM_MESSAGE_LENGTH = 25
Global Const IDSM_ITM_WEB_FORM_ENCODED = 26
Global Const IDSM_ITM_WEB_FORM_FIELD = 27
Global Const IDSM_ITM_WEB_FORM_VALUE = 28
Global Const IDSM_ITM_BAD_RECIPIENT = 29
Global Const IDSM_ITM_ALTERNATIVE_COUNT = 30
Global Const IDSM_ITM_UIDL = 31

'--- Address Book Items ---
Global Const IDSM_ITM_AB_NAME = 100
Global Const IDSM_ITM_AB_ADDRESS = 101
Global Const IDSM_ITM_AB_COMMENTS = 105
Global Const IDSM_ITM_AB_NAME_ADDRESS = 102
Global Const IDSM_ITM_AB_NAME_COMMENTS = 103
Global Const IDSM_ITM_AB_NAMEADDRESS_COMMENTS = 104

Global Const IDSM_ENC_NONE = 0
Global Const IDSM_ENC_UUENCODE = 1
Global Const IDSM_ENC_MIME = 2
Global Const IDSM_ENC_ZIP = 16
Global Const IDSM_ENC_NO_ZIP = 0
Global Const IDSM_ENC_ZIP_TOGETHER = 32
Global Const IDSM_ENC_ZIP_SEPARATELY = 0
Global Const IDSM_ENC_ZIP_ALL_SYSTEMS = 64
Global Const IDSM_ENC_ZIP_INTERNET_ONLY = 0
Global Const IDSM_ENC_ENC_ALL_SYSTEMS = 128
Global Const IDSM_ENC_ENC_INTERNET_ONLY = 0

Global Const IDSM_PROGBAR_NONE = 0
Global Const IDSM_PROGBAR_SEND = 1
Global Const IDSM_PROGBAR_RECEIVE = 2
Global Const IDSM_PROGBAR_CANCEL_BTN = 4

Global Const IDSM_STATE_UNKNOWN = 0
Global Const IDSM_STATE_UNREAD = -1
Global Const IDSM_STATE_READ = 1
Global Const IDSM_STATE_UNSENT = 2
Global Const IDSM_STATE_SENT = 3

Global Const IDSM_IMPORTANCE_LOWEST = 5
Global Const IDSM_IMPORTANCE_LOW = 4
Global Const IDSM_IMPORTANCE_NORMAL = 3
Global Const IDSM_IMPORTANCE_HIGH = 2
Global Const IDSM_IMPORTANCE_HIGHEST = 1

Global Const IDSM_PRIORITY_LOW = 4
Global Const IDSM_PRIORITY_NORMAL = 3
Global Const IDSM_PRIORITY_HIGH = 2

Global Const IDSM_DELIVERY_REPORT_NONE = 0
Global Const IDSM_DELIVERY_REPORT_ON_FAILURE = 1
Global Const IDSM_DELIVERY_REPORT_CONFIRM = 2
Global Const IDSM_DELIVERY_REPORT_TRACE = 3

Global Const IDSM_SENS_NORMAL = 0
Global Const IDSM_SENS_PERSONAL = 1
Global Const IDSM_SENS_CONFIDENTIAL = 2
Global Const IDSM_SENS_PRIVATE = 3
Global Const IDSM_SENS_THANK_YOU = 4
Global Const IDSM_SENS_FLAME = 5
Global Const IDSM_SENS_GOOD_JOB = 6
Global Const IDSM_SENS_JOKE = 7
Global Const IDSM_SENS_FYI = 8
Global Const IDSM_SENS_QUESTION = 9
Global Const IDSM_SENS_REMINDER = 10

Global Const IDSM_DATEFORMAT_GENERAL = 0
Global Const IDSM_DATEFORMAT_SHORT = 1
Global Const IDSM_DATEFORMAT_MEDIUM = 2
Global Const IDSM_DATEFORMAT_LONG = 3
Global Const IDSM_DATEFORMAT_NATIVE = 4
Global Const IDSM_DATEFORMAT_FIXED = 5

Global Const IDSM_SERVER_16BIT = 16
Global Const IDSM_SERVER_32BIT = 32

Global Const IDSM_NO_UTC_OFFSET = -50

Global Const IDSM_MESSAGE_LOG$ = "IDSM_MESSAGE_LOG"
Global Const IDSM_ITEM_LIST = "ITEM_LIST"

Global Const IDSM_OBJTYPE_NOTIFY = 0

Global Const IDSM_ASYNCH_COMPLETION_ONLY = 0
Global Const IDSM_ASYNCH_PROGRESS = 1

Global Const IDSM_METHOD_LOAD_HEADERS = 1
Global Const IDSM_METHOD_LOAD_MESSAGE = 2
Global Const IDSM_METHOD_DELETE = 3
Global Const IDSM_METHOD_SEND = 4
Global Const IDSM_METHOD_ABORT = 5
Global Const IDSM_METHOD_LOAD_IDENTIFIERS = 6

Global Const IDSM_EVENT_INACTIVE = 0
Global Const IDSM_EVENT_PROGRESS = 1
Global Const IDSM_EVENT_COMPLETE = 2

Global Const IDSM_AB_DLG_SINGLE = 1
Global Const IDSM_AB_DLG_MULTIPLE = 2

Global Const IDSM_AB_PUBLIC = "PUBLIC"
Global Const IDSM_AB_PRIVATE = "PRIVATE"

Global Const IDSM_AB_DISPTYPE_USER = 0
Global Const IDSM_AB_DISPTYPE_DISTLIST = 1
Global Const IDSM_AB_DISPTYPE_FORUM = 2
Global Const IDSM_AB_DISPTYPE_AGENT = 3
Global Const IDSM_AB_DISPTYPE_ORG = 4
Global Const IDSM_AB_DISPTYPE_PVT_DISTLIST = 5
Global Const IDSM_AB_DISPTYPE_REMOTE_USER = 6

Global Const IDSM_AB_UNKNOWN_COUNT = &H7FFFFFFF

Global Const IDSM_BASE_ERROR = &H80040000
Global Const IDSM_ERR_SOURCE = "IDSMailInterface.Server"

Global Const IDSM_ERR_UNDETERMINED = 513
Global Const IDSM_ERR_UNDETERMINED_UI = 514
Global Const IDSM_ERR_NOMAIL = 515
Global Const IDSM_ERR_NOADDRESSEES = 516
Global Const IDSM_ERR_TOOMANY_BCC = 517
Global Const IDSM_ERR_TOOMANY_CC = 518
Global Const IDSM_ERR_TOOMANY_TO = 519
Global Const IDSM_ERR_TOOMANY_ATTACHMENTS = 520
Global Const IDSM_ERR_INVALID_ATTACHMENT = 521
Global Const IDSM_ERR_USER_ABORT = 522
Global Const IDSM_ERR_NO_OBJECT_KEY = 523
Global Const IDSM_ERR_BAD_OBJECT_KEY = 524
Global Const IDSM_ERR_NO_LICENSE = 525
Global Const IDSM_ERR_INVALID_LICENSE = 526
Global Const IDSM_ERR_EXPIRED_LICENSE = 527
Global Const IDSM_ERR_UNAUTHORIZED = 528
Global Const IDSM_ERR_INVALID_PROPERTY = 529
Global Const IDSM_ERR_NOT_SUPPORTED = 530
Global Const IDSM_ERR_NOT_PROFESSIONAL = 531
Global Const IDSM_ERR_NO_HEADERS = 532
Global Const IDSM_ERR_BAD_MESSAGE_INDEX = 533
Global Const IDSM_ERR_ZIP = 534
Global Const IDSM_ERR_ENCODE = 535
Global Const IDSM_ERR_ASYNCH_REGISTER = 536
Global Const IDSM_ERR_ASYNCH_UNREGISTER = 537
Global Const IDSM_ERR_NO_ASYNCH_OBJECT = 538
Global Const IDSM_ERR_ASYNCH_ABORT = 539
Global Const IDSM_ERR_ASYNCH_IN_PROGRESS = 540
Global Const IDSM_ERR_ASYNCH_RECURSION = 541
Global Const IDSM_ERR_BAD_OBJ_TYPE = 542
Global Const IDSM_ERR_BAD_OBJ_CONFIG = 543
Global Const IDSM_ERR_NO_LOGIN_INFO = 544
Global Const IDSM_ERR_RESERVED_HEADER = 545
Global Const IDSM_ERR_NO_POST_OFFICE = 546
Global Const IDSM_ERR_NO_FILE = 547
Global Const IDSM_ERR_FILE_NOT_EXIST = 548
Global Const IDSM_ERR_FILE_IO = 549
Global Const IDSM_ERR_NO_RAS = 550
Global Const IDSM_ERR_MISSING_DATA = 551

Global Const IDSM_ERR_AB_NO_MAIL_OBJECT = 750
Global Const IDSM_ERR_AB_NOT_OPEN = 751
Global Const IDSM_ERR_AB_NO_MAIL_SYSTEM = 752
Global Const IDSM_ERR_AB_NO_SUPPORT_SYS = 753
Global Const IDSM_ERR_AB_NO_SUPPORT_FUNC = 754
Global Const IDSM_ERR_AB_NO_CURRENT_REC = 755
Global Const IDSM_ERR_AB_NO_ENTRIES = 756

Global Const IDSM_BASE_SVR_ERROR_MAPI = 2000
Global Const IDSM_BASE_SVR_ERROR_VINES = 3000
Global Const IDSM_BASE_SVR_ERROR_VIM = 4000
Global Const IDSM_BASE_SVR_ERROR_MHS = 5000
Global Const IDSM_BASE_SVR_ERROR_SMTP_POP = 6000
Global Const IDSM_BASE_SVR_ERROR_RAS = 7000
Global Const IDSM_BASE_SVR_ERROR_ACTV_MSG = 8000
Global Const IDSM_BASE_SVR_ERROR_NOTES = 9000


